-- 코드를 입력하세요
select INGREDIENT_TYPE, sum(CASE WHEN INGREDIENT_TYPE in ('sugar_based', 'fruit_based') THEN TOTAL_ORDER END) as TOTAL_ORDER
from FIRST_HALF 
join ICECREAM_INFO on FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR  
group by INGREDIENT_TYPE
order by TOTAL_ORDER; 